<head></head>
<body>
<font face="arial, serif" size="3">
    <font color="darkgrey" size="6">Today's Report:</font><br><br>
    <img height="25" width="25" src="https://looker.com/assets/img/images/favicons2/favicon-32x32.png"> Looker instance: https://lookerv716.dev.looker.com
    <br>
    <img height="25" width="25" src="https://looker.com/assets/img/images/favicons2/favicon-32x32.png"> Looker version: 7.16.16
    <br>
    <br><img height="30" width="30" src="https://img.icons8.com/ios/50/000000/socrates.png"> <strong><font color="darkgrey" size="6"> Users Summary</font></strong><br>
    <b>468 Users in the instance.</b> <a href=https://lookerv716.dev.looker.com/admin/users>[See Them...]</a><br>
    
            Disabled Looker users: 3<br>
        
            Locked Out Looker users: 0<br>
        
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/cotton/64/000000/greek-pillar-base.png"> <strong><font color="darkgrey" size="6"> Projects LookML Validation</font></strong><br>
        74 projects in the instance.
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/ios/64/000000/greek-helmet.png"> <strong><font color="darkgrey" size="6"> Content Validation</font></strong><br>
        229 content with errors in the instance.<br>
        <b>Errors for Looks</b>:<br>
        154 Looks failed Content Validation <a href=https://lookerv716.dev.looker.com/content_validator>[Fix Them...]</a><br>
        
            <li>Look 150 titled "A10" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 182 titled "D6" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 227 titled "H3" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 257 titled "J9" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 179 titled "D3" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 245 titled "I9" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 188 titled "E0" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 240 titled "I4" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 269 titled "K9" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 200 titled "F0" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 272 titled "L0" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 198 titled "E10" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 191 titled "E3" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 162 titled "B10" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 176 titled "D0" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 219 titled "G7" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 254 titled "J6" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 166 titled "C2" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 274 titled "L2" has this error: 'Unknown explore "users".'</li>
        
            <li>Look 181 titled "D5" has this error: 'Unknown explore "users".'</li>
        
            <li>...</li>
        <br><br>
        <b>Errors for Dashboards</b>:<br>
        33 Dashboards failed Content Validation <a href=https://lookerv716.dev.looker.com/content_validator>[Fix Them...]</a><br>
        
            <li>Dashboard 45 titled "new parameter" has this error: 'Unknown model "flights_test".'</li>
        
            <li>Dashboard 346 titled "dx-4560" has this error: 'Unknown explore "sql_runner_query".'</li>
        
            <li>Dashboard 164 titled "table_next_dash" has this error: 'Unknown model "dave_test".'</li>
        
            <li>Dashboard 165 titled "Table Next Dashboard" has this error: 'Unknown model "dave_test".'</li>
        
            <li>Dashboard 196 titled "Map Repro" has this error: 'Unknown model "faa".'</li>
        
            <li>Dashboard 38 titled "user attribute test" has this error: 'Unknown explore "users".'</li>
        
            <li>Dashboard 263 titled "REPRO" has this error: 'Unknown explore "products".'</li>
        
            <li>Dashboard 122 titled "merge result spoil order" has this error: 'Unknown field "orders_test.created_day_of_week".'</li>
        
            <li>Dashboard 306 titled "pie chart test" has this error: 'Unknown model "danielle_ecom".'</li>
        
            <li>Dashboard 291 titled "User attribute to sql_table_name test" has this error: 'Unknown field "order_items.table_name".'</li>
        
            <li>Dashboard 264 titled "testing" has this error: 'Unknown field "users.country".'</li>
        
            <li>Dashboard 202 titled "Dashboard Drill Child" has this error: 'Unknown field "orders.count".'</li>
        
            <li>Dashboard 170 titled "Filter Test" has this error: 'Unknown model "the_look_new_lookml".'</li>
        
            <li>Dashboard 187 titled "content validator filter issue (copy)" has this error: 'Unknown field "users_ha.gender".'</li>
        
            <li>Dashboard 188 titled "content validator filter issue" has this error: 'Unknown field "users_ha.gender".'</li>
        
            <li>Dashboard 307 titled "html" has this error: 'Unknown field "users.gender".'</li>
        
            <li>Dashboard 347 titled "dx-4560 (copy)" has this error: 'Unknown explore "sql_runner_query".'</li>
        
            <li>Dashboard 149 titled "labels" has this error: 'Unknown explore "order_items".'</li>
        
            <li>Dashboard 233 titled "test_dash_beta" has this error: 'Unknown model "danielle_ecom".'</li>
        
            <li>Dashboard 161 titled "content validator filter issue" has this error: 'Unknown field "users_ha.gender".'</li>
        
            <li>...</li>
        
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/wired/50/000000/in-transit.png"> <strong><font color="darkgrey" size="6"> Schedules</font></strong><br>
        <b>2 failing schedules in the instance. </b><a href=https://lookerv716.dev.looker.com/admin/scheduled_jobs>[See Them...]</a><br>
        
                <li>Schedule 'A0' failed to send to email</li>
            
                <li>Schedule 'Filter Test' failed to send to email</li>
            
                <li>...</li>
            
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/metro/26/000000/table-1.png"> <strong><font color="darkgrey" size="6"> PDTs</font></strong><br>
        <b>14 PDTs failures in the instance. </b><a href=https://lookerv716.dev.looker.com/admin/pdts>[See Them...]</a><br>
        
                <li>PDT 'ga_articles_mck' failed on connection: thelook</li>
            
                <li>PDT 'first_plan_events' failed on connection: thelook</li>
            
                <li>PDT 'ga_articles_infinite_scroll_fix_mpr' failed on connection: thelook</li>
            
                <li>PDT 'ga_articles_mmm' failed on connection: thelook</li>
            
                <li>PDT 'bi_header' failed on connection: thelook</li>
            
                <li>PDT 'user_facts' failed on connection: thelook</li>
            
                <li>PDT 'pdt_aaa' failed on connection: thelook</li>
            
                <li>PDT 'ga_articles_infinite_scroll_fix_mmm' failed on connection: thelook</li>
            
                <li>PDT 'ga_articles_msl' failed on connection: thelook</li>
            
                <li>PDT 'customers_orgs' failed on connection: thelook</li>
            
                <li>PDT 'ga_articles_us' failed on connection: thelook</li>
            
                <li>PDT 'first_paid_plan_events' failed on connection: thelook</li>
            
                <li>PDT 'ga_paginated_article_id_us' failed on connection: thelook</li>
            
                <li>PDT 'integers' failed on connection: thelook</li>
            
                <li>...</li>
            
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/pastel-glyph/64/000000/speedometer.png"> <strong><font color="darkgrey" size="6"> Performance</font></strong><br>
        <b>0 users have ran queries with more than 5000 rows from these sources: []. </b><a href=https://lookerv716.dev.looker.com/x/Fkc4lmxi1uAjGswpMJUyOf>[See Them...]</a><br>
        <br>
        
            The instance has one node.
        
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/wired/64/000000/database-restore.png"> <strong><font color="darkgrey" size="6"> Connectivity</font></strong><br>
        <b>23 connections in the instance. </b><a href=https://lookerv716.dev.looker.com/admin/connections>[See Them...]</a><br>
            
                <li>No issues found.</li>
            
    <hr>
    <br><img height="30" width="30" src="https://img.icons8.com/ios/50/000000/decentralized-network.png"> <strong><font color="darkgrey" size="6"> Connectivity</font></strong><br>
        <b>47 integrations in the instance. </b><a href=https://lookerv716.dev.looker.com/admin/actions>[See Them...]</a><br>
            
                <li>Integration Google Drive connectivity test successful</li>
            
                <li>Integration Google Sheets connectivity test successful</li>
            
                <li>Integration Google Cloud Storage connectivity test successful</li>
            
                <li>Integration Kloudio connectivity test successful</li>
            
                <li>Integration Segment Identify connectivity test could not run due to {"message":"Not found","documentation_url":"http://docs.looker.com/"}</li>
            
                <li>Integration Segment Group connectivity test could not run due to {"message":"Not found","documentation_url":"http://docs.looker.com/"}</li>
            
                <li>Integration Segment Track connectivity test successful</li>
            
                <li>Integration Slack Attachment (API Token) connectivity test failed</li>
            
                <li>Integration Slack connectivity test successful</li>
            
                <li>Integration Zapier connectivity test successful</li>
            
                <li>Integration Slack Attachment connectivity test failed</li>
            
                <li>...</li>
            

        <b>48 datagroups in the instance. </b><a href=https://lookerv716.dev.looker.com/admin/datagroups>[See Them...]</a><br>
            
                <li>Datagroup "ga_data_refresh" on model "hmi_ga" has this error:	(conn=11716306) Table 'demo_db.haymarketmediainc.172931887.ga_sessions_20*' doesn't exist</li>
            
                <li>Datagroup "ga_data_refresh_mmm" on model "hmi_ga" has this error:	(conn=11716307) Table 'demo_db.haymarketmediainc.58101377.ga_sessions_20*' doesn't exist</li>
            
                <li>Datagroup "ga_data_refresh_msl" on model "hmi_ga" has this error:	(conn=11716308) Table 'demo_db.haymarketmediainc.158240547.ga_sessions_20*' doesn't exist</li>
            
                <li>Datagroup "ga_data_refresh_mck" on model "hmi_ga" has this error:	(conn=11716309) Table 'demo_db.haymarketmediainc.2645226.ga_sessions_20*' doesn't exist</li>
            
                <li>...</li>
            
    <br><br>
    <font color="#5a748d" size="1">
        Find more information <a href="https://github.com/llooker/themis">go to the repo</a>
    <br>
        Something Wrong? <a href="https://github.com/llooker/themis/issues">Tell us</a>
    <br>
        All icons provided by Icons8: https://icons8.com
    </font>
</font>
</body>